// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: category.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    user_id,
    name,
    type,
    color,
    sort_order,
    is_default,
    created_at
FROM categories
WHERE user_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.SortOrder,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
