// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: expense.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    user_id,
    category_id,
    amount,
    description,
    expense_date,
    payment_method,
    memo,
    is_planned,
    planned_date
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9
         )
    RETURNING id, user_id, category_id, amount, description, expense_date, payment_method, memo, created_at, updated_at, is_planned, planned_date
`

type CreateExpenseParams struct {
	UserID        pgtype.UUID    `json:"user_id"`
	CategoryID    pgtype.UUID    `json:"category_id"`
	Amount        pgtype.Numeric `json:"amount"`
	Description   *string        `json:"description"`
	ExpenseDate   pgtype.Date    `json:"expense_date"`
	PaymentMethod *string        `json:"payment_method"`
	Memo          *string        `json:"memo"`
	IsPlanned     bool           `json:"is_planned"`
	PlannedDate   pgtype.Date    `json:"planned_date"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.ExpenseDate,
		arg.PaymentMethod,
		arg.Memo,
		arg.IsPlanned,
		arg.PlannedDate,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.PaymentMethod,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanned,
		&i.PlannedDate,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT
    e.id,
    e.user_id,
    e.category_id,
    e.amount,
    e.description,
    e.expense_date,
    e.payment_method,
    e.memo,
    e.is_planned,
    e.planned_date,
    e.created_at,
    e.updated_at,
    c.name AS category_name
FROM expenses e
LEFT JOIN categories c ON e.category_id = c.id
WHERE e.id = $1 AND e.user_id = $2
`

type GetExpenseParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetExpenseRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Description   *string          `json:"description"`
	ExpenseDate   pgtype.Date      `json:"expense_date"`
	PaymentMethod *string          `json:"payment_method"`
	Memo          *string          `json:"memo"`
	IsPlanned     bool             `json:"is_planned"`
	PlannedDate   pgtype.Date      `json:"planned_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CategoryName  *string          `json:"category_name"`
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (GetExpenseRow, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.UserID)
	var i GetExpenseRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.PaymentMethod,
		&i.Memo,
		&i.IsPlanned,
		&i.PlannedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT
    e.id,
    e.user_id,
    e.category_id,
    e.amount,
    e.description,
    e.expense_date,
    e.payment_method,
    e.memo,
    e.is_planned,
    e.planned_date,
    e.created_at,
    e.updated_at,
    c.name AS category_name
FROM expenses e
LEFT JOIN categories c ON e.category_id = c.id
WHERE e.user_id = $1 AND e.is_planned = FALSE
ORDER BY e.expense_date DESC
`

type ListExpensesRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Description   *string          `json:"description"`
	ExpenseDate   pgtype.Date      `json:"expense_date"`
	PaymentMethod *string          `json:"payment_method"`
	Memo          *string          `json:"memo"`
	IsPlanned     bool             `json:"is_planned"`
	PlannedDate   pgtype.Date      `json:"planned_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CategoryName  *string          `json:"category_name"`
}

func (q *Queries) ListExpenses(ctx context.Context, userID pgtype.UUID) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesRow
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.ExpenseDate,
			&i.PaymentMethod,
			&i.Memo,
			&i.IsPlanned,
			&i.PlannedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByDateRange = `-- name: ListExpensesByDateRange :many
SELECT
    e.id,
    e.user_id,
    e.category_id,
    e.amount,
    e.description,
    e.expense_date,
    e.payment_method,
    e.memo,
    e.is_planned,
    e.planned_date,
    e.created_at,
    e.updated_at,
    c.name AS category_name
FROM expenses e
         LEFT JOIN categories c ON e.category_id = c.id
WHERE e.user_id = $1
  AND e.is_planned = FALSE
  AND e.expense_date BETWEEN $2 AND $3
ORDER BY e.expense_date DESC
`

type ListExpensesByDateRangeParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type ListExpensesByDateRangeRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Description   *string          `json:"description"`
	ExpenseDate   pgtype.Date      `json:"expense_date"`
	PaymentMethod *string          `json:"payment_method"`
	Memo          *string          `json:"memo"`
	IsPlanned     bool             `json:"is_planned"`
	PlannedDate   pgtype.Date      `json:"planned_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CategoryName  *string          `json:"category_name"`
}

func (q *Queries) ListExpensesByDateRange(ctx context.Context, arg ListExpensesByDateRangeParams) ([]ListExpensesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByDateRange, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesByDateRangeRow
	for rows.Next() {
		var i ListExpensesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.ExpenseDate,
			&i.PaymentMethod,
			&i.Memo,
			&i.IsPlanned,
			&i.PlannedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedExpenses = `-- name: ListPlannedExpenses :many
SELECT
    e.id,
    e.user_id,
    e.category_id,
    e.amount,
    e.description,
    e.expense_date,
    e.payment_method,
    e.memo,
    e.is_planned,
    e.planned_date,
    e.created_at,
    e.updated_at,
    c.name AS category_name
FROM expenses e
         LEFT JOIN categories c ON e.category_id = c.id
WHERE e.user_id = $1 AND e.is_planned = TRUE AND e.planned_date > CURRENT_DATE
ORDER BY e.planned_date ASC
`

type ListPlannedExpensesRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Description   *string          `json:"description"`
	ExpenseDate   pgtype.Date      `json:"expense_date"`
	PaymentMethod *string          `json:"payment_method"`
	Memo          *string          `json:"memo"`
	IsPlanned     bool             `json:"is_planned"`
	PlannedDate   pgtype.Date      `json:"planned_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CategoryName  *string          `json:"category_name"`
}

func (q *Queries) ListPlannedExpenses(ctx context.Context, userID pgtype.UUID) ([]ListPlannedExpensesRow, error) {
	rows, err := q.db.Query(ctx, listPlannedExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlannedExpensesRow
	for rows.Next() {
		var i ListPlannedExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.ExpenseDate,
			&i.PaymentMethod,
			&i.Memo,
			&i.IsPlanned,
			&i.PlannedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses SET
                    category_id    = $1,
                    amount         = $2,
                    description    = $3,
                    expense_date   = $4,
                    payment_method = $5,
                    memo           = $6,
                    is_planned     = $7,
                    planned_date   = $8,
                    updated_at     = CURRENT_TIMESTAMP
WHERE id = $9 AND user_id = $10
    RETURNING id, user_id, category_id, amount, description, expense_date, payment_method, memo, created_at, updated_at, is_planned, planned_date
`

type UpdateExpenseParams struct {
	CategoryID    pgtype.UUID    `json:"category_id"`
	Amount        pgtype.Numeric `json:"amount"`
	Description   *string        `json:"description"`
	ExpenseDate   pgtype.Date    `json:"expense_date"`
	PaymentMethod *string        `json:"payment_method"`
	Memo          *string        `json:"memo"`
	IsPlanned     bool           `json:"is_planned"`
	PlannedDate   pgtype.Date    `json:"planned_date"`
	ID            pgtype.UUID    `json:"id"`
	UserID        pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.ExpenseDate,
		arg.PaymentMethod,
		arg.Memo,
		arg.IsPlanned,
		arg.PlannedDate,
		arg.ID,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.PaymentMethod,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPlanned,
		&i.PlannedDate,
	)
	return i, err
}
