// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: income.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncome = `-- name: CreateIncome :one
INSERT INTO incomes (
    user_id,
    category_id,
    amount,
    description,
    income_date,
    memo
) VALUES (
             $1, $2, $3, $4, $5, $6
         )
    RETURNING id, user_id, category_id, amount, description, income_date, memo, created_at, updated_at
`

type CreateIncomeParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Description *string        `json:"description"`
	IncomeDate  pgtype.Date    `json:"income_date"`
	Memo        *string        `json:"memo"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.IncomeDate,
		arg.Memo,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.IncomeDate,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :exec
DELETE FROM incomes
WHERE id = $1 AND user_id = $2
`

type DeleteIncomeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteIncome(ctx context.Context, arg DeleteIncomeParams) error {
	_, err := q.db.Exec(ctx, deleteIncome, arg.ID, arg.UserID)
	return err
}

const getIncome = `-- name: GetIncome :one
SELECT
    i.id,
    i.user_id,
    i.category_id,
    i.amount,
    i.description,
    i.income_date,
    i.memo,
    i.created_at,
    i.updated_at,
    c.name AS category_name
FROM incomes i
         LEFT JOIN categories c ON i.category_id = c.id
WHERE i.id = $1 AND i.user_id = $2
`

type GetIncomeParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetIncomeRow struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	CategoryID   pgtype.UUID      `json:"category_id"`
	Amount       pgtype.Numeric   `json:"amount"`
	Description  *string          `json:"description"`
	IncomeDate   pgtype.Date      `json:"income_date"`
	Memo         *string          `json:"memo"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	CategoryName *string          `json:"category_name"`
}

func (q *Queries) GetIncome(ctx context.Context, arg GetIncomeParams) (GetIncomeRow, error) {
	row := q.db.QueryRow(ctx, getIncome, arg.ID, arg.UserID)
	var i GetIncomeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.IncomeDate,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const listIncomes = `-- name: ListIncomes :many
SELECT
    i.id,
    i.user_id,
    i.category_id,
    i.amount,
    i.description,
    i.income_date,
    i.memo,
    i.created_at,
    i.updated_at,
    c.name AS category_name
FROM incomes i
         LEFT JOIN categories c ON i.category_id = c.id
WHERE i.user_id = $1 AND i.income_date <= CURRENT_DATE
ORDER BY i.income_date DESC
`

type ListIncomesRow struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	CategoryID   pgtype.UUID      `json:"category_id"`
	Amount       pgtype.Numeric   `json:"amount"`
	Description  *string          `json:"description"`
	IncomeDate   pgtype.Date      `json:"income_date"`
	Memo         *string          `json:"memo"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	CategoryName *string          `json:"category_name"`
}

func (q *Queries) ListIncomes(ctx context.Context, userID pgtype.UUID) ([]ListIncomesRow, error) {
	rows, err := q.db.Query(ctx, listIncomes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomesRow
	for rows.Next() {
		var i ListIncomesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.IncomeDate,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomesByDateRange = `-- name: ListIncomesByDateRange :many
SELECT
    i.id,
    i.user_id,
    i.category_id,
    i.amount,
    i.description,
    i.income_date,
    i.memo,
    i.created_at,
    i.updated_at,
    c.name AS category_name
FROM incomes i
         LEFT JOIN categories c ON i.category_id = c.id
WHERE i.user_id = $1
  AND i.income_date BETWEEN $2 AND $3
ORDER BY i.income_date DESC
`

type ListIncomesByDateRangeParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	IncomeDate   pgtype.Date `json:"income_date"`
	IncomeDate_2 pgtype.Date `json:"income_date_2"`
}

type ListIncomesByDateRangeRow struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	CategoryID   pgtype.UUID      `json:"category_id"`
	Amount       pgtype.Numeric   `json:"amount"`
	Description  *string          `json:"description"`
	IncomeDate   pgtype.Date      `json:"income_date"`
	Memo         *string          `json:"memo"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	CategoryName *string          `json:"category_name"`
}

func (q *Queries) ListIncomesByDateRange(ctx context.Context, arg ListIncomesByDateRangeParams) ([]ListIncomesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listIncomesByDateRange, arg.UserID, arg.IncomeDate, arg.IncomeDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomesByDateRangeRow
	for rows.Next() {
		var i ListIncomesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.IncomeDate,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedIncomes = `-- name: ListPlannedIncomes :many
SELECT
    i.id,
    i.user_id,
    i.category_id,
    i.amount,
    i.description,
    i.income_date,
    i.memo,
    i.created_at,
    i.updated_at,
    c.name AS category_name
FROM incomes i
         LEFT JOIN categories c ON i.category_id = c.id
WHERE i.user_id = $1 AND i.income_date > CURRENT_DATE
ORDER BY i.income_date ASC
`

type ListPlannedIncomesRow struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	CategoryID   pgtype.UUID      `json:"category_id"`
	Amount       pgtype.Numeric   `json:"amount"`
	Description  *string          `json:"description"`
	IncomeDate   pgtype.Date      `json:"income_date"`
	Memo         *string          `json:"memo"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	CategoryName *string          `json:"category_name"`
}

func (q *Queries) ListPlannedIncomes(ctx context.Context, userID pgtype.UUID) ([]ListPlannedIncomesRow, error) {
	rows, err := q.db.Query(ctx, listPlannedIncomes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlannedIncomesRow
	for rows.Next() {
		var i ListPlannedIncomesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.IncomeDate,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE incomes SET
                   category_id  = $1,
                   amount       = $2,
                   description  = $3,
                   income_date  = $4,
                   memo         = $5,
                   updated_at   = CURRENT_TIMESTAMP
WHERE id = $6 AND user_id = $7
    RETURNING id, user_id, category_id, amount, description, income_date, memo, created_at, updated_at
`

type UpdateIncomeParams struct {
	CategoryID  pgtype.UUID    `json:"category_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Description *string        `json:"description"`
	IncomeDate  pgtype.Date    `json:"income_date"`
	Memo        *string        `json:"memo"`
	ID          pgtype.UUID    `json:"id"`
	UserID      pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.IncomeDate,
		arg.Memo,
		arg.ID,
		arg.UserID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.IncomeDate,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
