// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	Color     *string          `json:"color"`
	SortOrder int32            `json:"sort_order"`
	IsDefault bool             `json:"is_default"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Expense struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Description   *string          `json:"description"`
	ExpenseDate   pgtype.Date      `json:"expense_date"`
	PaymentMethod *string          `json:"payment_method"`
	Memo          *string          `json:"memo"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	IsPlanned     bool             `json:"is_planned"`
	PlannedDate   pgtype.Date      `json:"planned_date"`
}

type Income struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	Amount      pgtype.Numeric   `json:"amount"`
	Description *string          `json:"description"`
	IncomeDate  pgtype.Date      `json:"income_date"`
	Memo        *string          `json:"memo"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	IsPlanned   bool             `json:"is_planned"`
	PlannedDate pgtype.Date      `json:"planned_date"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Email        string           `json:"email"`
	PasswordHash *string          `json:"password_hash"`
	Provider     string           `json:"provider"`
	ProviderID   *string          `json:"provider_id"`
	Name         *string          `json:"name"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
