// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: recurring_expense.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO recurring_expenses (
    user_id,
    category_id,
    amount,
    description,
    payment_method,
    memo,
    billing_day,
    start_date,
    end_date
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9
         )
    RETURNING id, user_id, category_id, amount, description, payment_method, memo, billing_day, start_date, end_date, is_active, created_at, updated_at
`

type CreateRecurringExpenseParams struct {
	UserID        pgtype.UUID    `json:"user_id"`
	CategoryID    pgtype.UUID    `json:"category_id"`
	Amount        pgtype.Numeric `json:"amount"`
	Description   *string        `json:"description"`
	PaymentMethod *string        `json:"payment_method"`
	Memo          *string        `json:"memo"`
	BillingDay    int32          `json:"billing_day"`
	StartDate     pgtype.Date    `json:"start_date"`
	EndDate       pgtype.Date    `json:"end_date"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, createRecurringExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.PaymentMethod,
		arg.Memo,
		arg.BillingDay,
		arg.StartDate,
		arg.EndDate,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.PaymentMethod,
		&i.Memo,
		&i.BillingDay,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecurringExpenseLog = `-- name: CreateRecurringExpenseLog :one
INSERT INTO recurring_expense_logs (
    recurring_expense_id,
    expense_id,
    billing_year,
    billing_month
) VALUES (
             $1, $2, $3, $4
         )
    RETURNING id, recurring_expense_id, expense_id, billing_year, billing_month, created_at
`

type CreateRecurringExpenseLogParams struct {
	RecurringExpenseID pgtype.UUID `json:"recurring_expense_id"`
	ExpenseID          pgtype.UUID `json:"expense_id"`
	BillingYear        int32       `json:"billing_year"`
	BillingMonth       int32       `json:"billing_month"`
}

func (q *Queries) CreateRecurringExpenseLog(ctx context.Context, arg CreateRecurringExpenseLogParams) (RecurringExpenseLog, error) {
	row := q.db.QueryRow(ctx, createRecurringExpenseLog,
		arg.RecurringExpenseID,
		arg.ExpenseID,
		arg.BillingYear,
		arg.BillingMonth,
	)
	var i RecurringExpenseLog
	err := row.Scan(
		&i.ID,
		&i.RecurringExpenseID,
		&i.ExpenseID,
		&i.BillingYear,
		&i.BillingMonth,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecurringExpense = `-- name: DeleteRecurringExpense :exec
DELETE FROM recurring_expenses
WHERE id = $1 AND user_id = $2
`

type DeleteRecurringExpenseParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteRecurringExpense(ctx context.Context, arg DeleteRecurringExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringExpense, arg.ID, arg.UserID)
	return err
}

const getRecurringExpense = `-- name: GetRecurringExpense :one
SELECT
    r.id,
    r.user_id,
    r.category_id,
    r.amount,
    r.description,
    r.payment_method,
    r.memo,
    r.billing_day,
    r.start_date,
    r.end_date,
    r.is_active,
    r.created_at,
    r.updated_at,
    c.name AS category_name
FROM recurring_expenses r
         LEFT JOIN categories c ON r.category_id = c.id
WHERE r.id = $1 AND r.user_id = $2
`

type GetRecurringExpenseParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetRecurringExpenseRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Description   *string          `json:"description"`
	PaymentMethod *string          `json:"payment_method"`
	Memo          *string          `json:"memo"`
	BillingDay    int32            `json:"billing_day"`
	StartDate     pgtype.Date      `json:"start_date"`
	EndDate       pgtype.Date      `json:"end_date"`
	IsActive      bool             `json:"is_active"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CategoryName  *string          `json:"category_name"`
}

func (q *Queries) GetRecurringExpense(ctx context.Context, arg GetRecurringExpenseParams) (GetRecurringExpenseRow, error) {
	row := q.db.QueryRow(ctx, getRecurringExpense, arg.ID, arg.UserID)
	var i GetRecurringExpenseRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.PaymentMethod,
		&i.Memo,
		&i.BillingDay,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const getRecurringExpenseLog = `-- name: GetRecurringExpenseLog :one
SELECT id FROM recurring_expense_logs
WHERE recurring_expense_id = $1
  AND billing_year = $2
  AND billing_month = $3
`

type GetRecurringExpenseLogParams struct {
	RecurringExpenseID pgtype.UUID `json:"recurring_expense_id"`
	BillingYear        int32       `json:"billing_year"`
	BillingMonth       int32       `json:"billing_month"`
}

func (q *Queries) GetRecurringExpenseLog(ctx context.Context, arg GetRecurringExpenseLogParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRecurringExpenseLog, arg.RecurringExpenseID, arg.BillingYear, arg.BillingMonth)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listActiveRecurringExpenses = `-- name: ListActiveRecurringExpenses :many
SELECT
    r.id,
    r.user_id,
    r.category_id,
    r.amount,
    r.description,
    r.payment_method,
    r.memo,
    r.billing_day,
    r.start_date,
    r.end_date,
    r.is_active,
    r.created_at,
    r.updated_at,
    c.name AS category_name
FROM recurring_expenses r
         LEFT JOIN categories c ON r.category_id = c.id
WHERE r.user_id = $1
  AND r.is_active = TRUE
  AND r.start_date <= CURRENT_DATE
  AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE)
ORDER BY r.billing_day ASC
`

type ListActiveRecurringExpensesRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Description   *string          `json:"description"`
	PaymentMethod *string          `json:"payment_method"`
	Memo          *string          `json:"memo"`
	BillingDay    int32            `json:"billing_day"`
	StartDate     pgtype.Date      `json:"start_date"`
	EndDate       pgtype.Date      `json:"end_date"`
	IsActive      bool             `json:"is_active"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CategoryName  *string          `json:"category_name"`
}

func (q *Queries) ListActiveRecurringExpenses(ctx context.Context, userID pgtype.UUID) ([]ListActiveRecurringExpensesRow, error) {
	rows, err := q.db.Query(ctx, listActiveRecurringExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRecurringExpensesRow
	for rows.Next() {
		var i ListActiveRecurringExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.PaymentMethod,
			&i.Memo,
			&i.BillingDay,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringExpenses = `-- name: ListRecurringExpenses :many
SELECT
    r.id,
    r.user_id,
    r.category_id,
    r.amount,
    r.description,
    r.payment_method,
    r.memo,
    r.billing_day,
    r.start_date,
    r.end_date,
    r.is_active,
    r.created_at,
    r.updated_at,
    c.name AS category_name
FROM recurring_expenses r
         LEFT JOIN categories c ON r.category_id = c.id
WHERE r.user_id = $1
ORDER BY r.billing_day ASC
`

type ListRecurringExpensesRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Description   *string          `json:"description"`
	PaymentMethod *string          `json:"payment_method"`
	Memo          *string          `json:"memo"`
	BillingDay    int32            `json:"billing_day"`
	StartDate     pgtype.Date      `json:"start_date"`
	EndDate       pgtype.Date      `json:"end_date"`
	IsActive      bool             `json:"is_active"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CategoryName  *string          `json:"category_name"`
}

func (q *Queries) ListRecurringExpenses(ctx context.Context, userID pgtype.UUID) ([]ListRecurringExpensesRow, error) {
	rows, err := q.db.Query(ctx, listRecurringExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecurringExpensesRow
	for rows.Next() {
		var i ListRecurringExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.PaymentMethod,
			&i.Memo,
			&i.BillingDay,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :one
UPDATE recurring_expenses SET
                              category_id    = $1,
                              amount         = $2,
                              description    = $3,
                              payment_method = $4,
                              memo           = $5,
                              billing_day    = $6,
                              start_date     = $7,
                              end_date       = $8,
                              is_active      = $9,
                              updated_at     = CURRENT_TIMESTAMP
WHERE id = $10 AND user_id = $11
    RETURNING id, user_id, category_id, amount, description, payment_method, memo, billing_day, start_date, end_date, is_active, created_at, updated_at
`

type UpdateRecurringExpenseParams struct {
	CategoryID    pgtype.UUID    `json:"category_id"`
	Amount        pgtype.Numeric `json:"amount"`
	Description   *string        `json:"description"`
	PaymentMethod *string        `json:"payment_method"`
	Memo          *string        `json:"memo"`
	BillingDay    int32          `json:"billing_day"`
	StartDate     pgtype.Date    `json:"start_date"`
	EndDate       pgtype.Date    `json:"end_date"`
	IsActive      bool           `json:"is_active"`
	ID            pgtype.UUID    `json:"id"`
	UserID        pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpense,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.PaymentMethod,
		arg.Memo,
		arg.BillingDay,
		arg.StartDate,
		arg.EndDate,
		arg.IsActive,
		arg.ID,
		arg.UserID,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.PaymentMethod,
		&i.Memo,
		&i.BillingDay,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
