// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: summary.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sumActualExpenses = `-- name: SumActualExpenses :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC AS total
FROM expenses
WHERE user_id = $1
  AND expense_date <= CURRENT_DATE
`

func (q *Queries) SumActualExpenses(ctx context.Context, userID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumActualExpenses, userID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumActualIncomes = `-- name: SumActualIncomes :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC AS total
FROM incomes
WHERE user_id = $1
  AND income_date <= CURRENT_DATE
`

func (q *Queries) SumActualIncomes(ctx context.Context, userID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumActualIncomes, userID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumPlannedExpensesByDate = `-- name: SumPlannedExpensesByDate :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC AS total
FROM expenses
WHERE user_id = $1
  AND expense_date > CURRENT_DATE
  AND expense_date <= $2
`

type SumPlannedExpensesByDateParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ExpenseDate pgtype.Date `json:"expense_date"`
}

func (q *Queries) SumPlannedExpensesByDate(ctx context.Context, arg SumPlannedExpensesByDateParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumPlannedExpensesByDate, arg.UserID, arg.ExpenseDate)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumPlannedIncomesByDate = `-- name: SumPlannedIncomesByDate :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC AS total
FROM incomes
WHERE user_id = $1
  AND income_date > CURRENT_DATE
  AND income_date <= $2
`

type SumPlannedIncomesByDateParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	IncomeDate pgtype.Date `json:"income_date"`
}

func (q *Queries) SumPlannedIncomesByDate(ctx context.Context, arg SumPlannedIncomesByDateParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumPlannedIncomesByDate, arg.UserID, arg.IncomeDate)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}
